name: CI Test

on:
  pull_request:
    branches:
      - master

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: 'actions/setup-node@v1'
      with:
        node-version: 12
    - run: npm ci
    - run: npm run test
    - run: npm run build
